services:
  nominatim:
    image: mediagis/nominatim:4.4
    container_name: nominatim
    ports:
      - "8080:8080"
    environment:
      - PBF_PATH=/data/singapore.osm.pbf
      - REVERSE_ONLY=true
      - IMPORT_WIKIPEDIA=false
      - NOMINATIM_PASSWORD=password
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - nominatim-flatnode:/nominatim/flatnode
      - ~/Documents/osm:/data

volumes:
  nominatim-data:
  nominatim-flatnode:
